version: "3"
services:
   black-pearl:
      build: black-pearl
      depends_on:
         - whydah
      labels:
         - "traefik.http.routers.black-pearl.rule=Host(`aye-bucko.jogit.pl`)"
   whydah:
      build: .
      labels:
         - "traefik.http.routers.whydah.rule=Host(`srv.aye-bucko.jogit.pl`)"
