version: "3"
services:
   black-pearl:
      image: aye-bucko/black-pearl:${BRANCH_NAME}
      links:
         - whydah
      networks:
         - proxy
      labels:
         - traefik.enable=true
         - traefik.http.routers.black-pearl.rule=Host(`${FRONTEND_HOST}`)
         - traefik.http.routers.black-pearl.tls.certresolver=tls-challenge
         - traefik.docker.network=proxy

   whydah:
      image: aye-bucko/whydah:${BRANCH_NAME}
      networks:
         - proxy
      labels:
         - traefik.enable=true
         - traefik.http.routers.whydah.rule=Host(`${BACKEND_HOST}`)
         - traefik.http.routers.whydah.tls.certresolver=tls-challenge
         - traefik.docker.network=proxy

networks:
   proxy:
      external: false
