version: "3"
services:
   black-pearl:
      image: aye-bucko/black-pearl
      links:
         - whydah
      networks:
         - web
         - internal
      ports:
         - "9000:80"
      labels:
         - traefik.enable=true
         - traefik.http.routers.black-pearl.rule=Host(`aye-bucko.jogit.pl`)
         # - traefik.http.routers.black-pearl.entrypoints=websecure
         - traefik.http.routers.black-pearl.tls.certresolver=tls-challenge
         - traefik.docker.network=web

   whydah:
      image: aye-bucko/whydah
      networks:
         - web
         - internal
      ports:
         - "9001:3000"
      labels:
         - traefik.enable=true
         - traefik.http.routers.whydah.rule=Host(`srv.aye-bucko.jogit.pl`)
         - traefik.http.routers.black-pearl.tls.certresolver=tls-challenge
         - traefik.docker.network=web


networks:
   web:
      external: true
   internal:
      external: false
