name: Deploy game

on: push

jobs:
   build--black-pearl:
      name: Build Black Pearl (game frontend)
      runs-on: self-hosted
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '14'
         - run: npm -g install yarn
         - run: yarn install
         - run: |
              cd black-pearl
              echo "GAME_SERVER_URL=ws://srv.aye-bycko.jogit.pl" > .env
         - run: cd black-pearl && yarn build
         - run: cd black-pearl && docker build -t aye-bucko/black-pearl .

   build--whydah:
      name: Build Whydah (game backend)
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
             node-version: '14'
        - run: npm -g install yarn
        - run: yarn install
        - run: cd whydah && yarn build
        - run: docker build -t aye-bucko/whydah .

   deploy:
      name: Deploy
      runs-on: self-hosted
      needs:
         - build--black-pearl
         - build--whydah
      steps:
         - run: docker-compose up -d --force-recreate
